<?php
/**
 * @file
 * Main Atlast API file.
 */

/**
 * Implements hook_menu().
 */
function a_api_menu() {
  $items['api/%a_api_instance'] = array(
    'page callback' => 'a_api_main',
    'page arguments' => array(1, 2),
    'access arguments' => array('access atlast api'),
    'type' => MENU_CALLBACK,
    'delivery callback' => 'a_api_json_callback',
  );

  return $items;
}

/**
 * Menu loader, loads the instance argument.
 */
function a_api_instance_load($slug) {
  $uid = db_select('field_data_field_user_slug', 's')
  ->fields('s', array('entity_id'))
  ->condition('field_user_slug_machine', $slug,'=')
  ->execute()
  ->fetchField();

  if ($uid) {
    return user_load($uid);
  }
}

/**
 * Implements hook_permission().
 */
function a_api_permission() {
  return array(
    'access atlast api' =>  array(
      'title' => t('access Atlast API'),
      'description' => t('Access to the Atlast API'),
    ),
  );
}

/**
 * Delivery API callback.
 */
function a_api_json_callback($page_callback_result) {
  drupal_add_http_header('Content-Type', 'application/json');

  // Only render content
  print 'atlastApi(' . json_encode($page_callback_result, JSON_PRETTY_PRINT) . ')';
}

/**
 * Main API callback.
 */
function a_api_main($instance, $timestamp = NULL) {
  // If no instance was found.
  if (!$instance) {
    return array('error' => 'invalid slug');
  }

  $api = module_invoke_all('atlast_api', $instance, $timestamp);

  return $api;
}


/**
 * Implements hook_atlast_api().
 */
function a_api_atlast_api($instance, $timestamp) {
  $menu_items = module_invoke_all('atlast_api_menu_items', $instance);

  return array(
    'menu' => $menu_items
  );
}
