<?php
/**
 * @file
 * Code for the Atlast Instance feature.
 */

include_once 'a_instance.features.inc';

/**
 * Implements hook_form_FORM_ID_alter() for user_profile().
 */
function a_instance_form_user_profile_form_alter(&$form, &$form_state) {
  $form['#after_build'][] = 'a_instance_form_user_profile_form_after_build';
}

/**
 * Implements after build for user_profile().
 */
function a_instance_form_user_profile_form_after_build(&$form, &$form_state) {
  $form['#group_children']['revision_information'] = 'group_user_settings';
  return $form;
}

/**
 * Implements hook_atlast_api().
 */
function a_instance_atlast_api($instance, $timestamp) {
  if ($timestamp < $instance->revision_timestamp) {
    // Get bounds.
    $bounds_geojson = json_decode($instance->field_user_map_bounds[LANGUAGE_NONE][0]['value'], TRUE);

    sdpm($bounds_geojson['features'][0]['geometry']['coordinates'][0][1]);

    $bounds = array(
      'topLeft' => array(
        $bounds_geojson['features'][0]['geometry']['coordinates'][0][1][1],
        $bounds_geojson['features'][0]['geometry']['coordinates'][0][1][0]
      ),
      'bottomRight' => array(
        $bounds_geojson['features'][0]['geometry']['coordinates'][0][3][1],
        $bounds_geojson['features'][0]['geometry']['coordinates'][0][3][0]
      )
    );

    // Format the settings.
    $instance_formatted = array(
      'mapUrl' => $instance->field_user_map_url[LANGUAGE_NONE][0]['url'],
      'mapBounds' => $bounds,
    );

    return array(
      'instance' => $instance_formatted
    );
  }
}
